version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    labels:
      - "dependency"
    open-pull-requests-limit: 3
    schedule:
      interval: "weekly"

  - package-ecosystem: "pip"
    directory: "/src/hfp_challenge/challenge"
    labels:
      - "dependency"
    open-pull-requests-limit: 3
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker"
    directory: "/src/hfp_challenge/challenge"
    labels:
      - "dependency"
      - "docker"
    open-pull-requests-limit: 3
    schedule:
      interval: "weekly"
