services:
  challenge-api:
    image: redteamsubnet61/historical_fingerprinter:1.0.0
    build:
      context: ./src/hfp_challenge/challenge
    restart: unless-stopped
    privileged: true
    environment:
      TERM: ${TERM:-xterm}
      TZ: ${TZ:-UTC}
      HFP_CHALLENGE_API_PORT: ${HFP_CHALLENGE_API_PORT:-10001}
    env_file:
      - path: .env
        required: false
    volumes:
      - "./volumes/storage/historical_fingerprinter/logs:${HFP_CHALLENGE_API_LOGS_DIR:-/var/log/historical_fingerprinter                                                                                                                                                                                                                       }"
      - "./volumes/storage/historical_fingerprinter/data:${HFP_CHALLENGE_API_DATA_DIR:-/var/lib/historical_fingerprinter}"
    ports:
      - "${HFP_CHALLENGE_API_PORT:-10001}:${HFP_CHALLENGE_API_PORT:-10001}"
    tty: true
