services:
  miner-api:
    image: myhub/rest-hfp-commit:latest
    build:
      context: .
    restart: unless-stopped
    environment:
      TERM: ${TERM:-xterm}
      TZ: ${TZ:-UTC}
    ports:
      - 10002:10002
    tty: true
